# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This is a Kconfig fragment which can be used to enable debug-related options
# in the application. See the README for more details.

# compiler
CONFIG_DEBUG_OPTIMIZATIONS=y

# native sim
CONFIG_EMUL=y
# CONFIG_FUSE_FS_ACCESS=y

# CONFIG_DISK_DRIVERS=y
# CONFIG_DISK_DRIVER_FLASH=y
# CONFIG_DISK_ACCESS=y
# CONFIG_FAT_FILESYSTEM_ELM=y
# CONFIG_MAIN_STACK_SIZE=2048

# logging
CONFIG_LOG=y
CONFIG_APP_LOG_LEVEL_DBG=y
CONFIG_DAC_LOG_LEVEL_OFF=y