CONFIG_I2C=y
CONFIG_GPIO=y

CONFIG_SHELL=y
CONFIG_I2C_SHELL=y
CONFIG_GPIO_SHELL=y

CONFIG_LOG=y
CONFIG_APP_LOG_LEVEL_DBG=y

# CONFIG_FLASH=y
# CONFIG_FLASH_MAP=y
# CONFIG_FLASH_SHELL=y

# CONFIG_FILE_SYSTEM=y
# CONFIG_FILE_SYSTEM_SHELL=y

CONFIG_DAC=y
CONFIG_DMA=y
CONFIG_COMPILER_SAVE_TEMPS=y
# CONFIG_DYNAMIC_INTERRUPTS=y
CONFIG_SHARED_INTERRUPTS=y